### PR TITLE
Manual update from ferrocene/ferrocene

### PR DESCRIPTION
**Pull request by Hoverbear**
mirrored-commit: 8ac7393f92c3b9b16a6481488488ed04745c70c7

### CODE REVIEW

**Comment by amanjeev** [comment]
Just stating that these changes do not include changes still umerged in https://github.com/ferrocene/ferrocene/pull/1049. 

Would this basically unblock the mirror CI?

**Comment by amanjeev** [comment]
I am a bit confused with this. Your branch contains this file [ferrocene_intersphinx_support.py](https://github.com/ferrocene/sphinx-shared-resources/blob/hoverbear/manually-update/exts/ferrocene_intersphinx_support.py). 

[But no such file exists in ferrocene repo](https://github.com/ferrocene/ferrocene/tree/main/ferrocene/doc/sphinx-shared-resources/exts) in the same `exts` directory of `sphinx-shared-resources`.

**Comment by Hoverbear** [comment]
> Would this basically unblock the mirror CI?

That's my hope, yeah.

**Comment by Hoverbear** [comment]
@amanjeev I did a better job this time I think. Mind taking another look?

**Comment by amanjeev** [comment]
I think we missed one file deletion:

- in Ferrocene repo: `theme.conf` was deleted (`ferrocene/doc/sphinx-shared-resources/themes/ferrocene/theme.conf` was renamed to `ferrocene/doc/sphinx-shared-resources/themes/ferrocene/theme.toml`)
- in this repo we still have `theme.toml` as well as `theme.conf` and it must be deleted to achieve parity with ferrocene repo.

**Review by amanjeev — APPROVED** [review]
I approve this message.

**Comment by Hoverbear** [comment]
bors merge

**Comment by amanjeev** [comment]
I merged this given the intention of @Hoverbear with `borse merge` message is to merge this. We don't use bors in this repo.

**Pull request merged**
